baseURL = "https://IT-Berater.github.io/MindAPI/"
languageCode = "en-us"
title = "MindAPI"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Thomas Wenzlaff"
    description = "Bringing order to API hacking chaos"
    githubUsername = "IT-Berater"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Blinker" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    css = [ "css/custom.css" ]
    js = [
        "https://cdn.jsdelivr.net/npm/d3@6",
        "https://cdn.jsdelivr.net/npm/markmap-lib@0.11.6",
        "https://cdn.jsdelivr.net/npm/markmap-view@0.2.6",
        "js/mindmap.js"
    ]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/references/"
    name = "References"
    weight = 3

[[menu.main]]
    url = "/play/"
    name = "Play"
    weight = 4

[[menu.main]]
    url = "#download"
    identifier = "download"
    name = "Download"
    weight = 5

[[menu.main]]
    parent = "download"
    identifier = "interactive"
    url = "#download-interactive"
    name = "Interactive HTML"

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:davidsopas@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/dsopas/MindAPI"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/dsopas/"
    name = "fab fa-twitter"
    weight = 3
